spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: library_db

server:
  port: 8040

logging:
  level:
    ru.otus.hw: DEBUG

mongock:
  migration-scan-package: ru.otus.hw.migrations
  transaction-enabled: false
